name: Push Image to ACR

on:
  workflow_dispatch:
jobs:
  build:
   runs-on: ubuntu-latest
   defaults:
    run: 
     shell: bash
   steps:
   - name: Checkout the repository
     uses: actions/checkout@v2

   
   - name: Set up Docker Buildx 
     uses: docker/setup-buildx-action@v1
     
   - name: Azure Login
     uses: azure/docker-login@v1
     with:
       login-server: demopush.azurecr.io
       username: ${{ secrets.ACR_USERNAME }}
       password: ${{ secrets.ACR_PASSWORD }}
   - name: Build and push Docker image 
     uses: docker/build-push-action@v2 
     with: 
      context: . 
      file: ./Dockerfile 
      push: true 
      tags: demopush.azurecr.io/pythonapp:${{ github.sha }}


      
