name: Push image to ACR
env:
    resourceGroup: 'classrg'
    name: 'classcluster'
    kubernetesVersion: '1.30.6'

on:
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        
        steps:
            - name: Checkout the repo
              uses: actions/checkout@v2

            - name: Set up Docker
              uses: docker/setup-buildx-action@v1

            - name: Azure login
              uses: azure/docker-login@v1
              with:
                login-server: learnaksinclass.azurecr.io
                username: ${{secrets.ACR_USERNAME}}
                password: ${{secrets.ACR_PASSWORD}}

            - name: Build and Push
              uses: docker/build-push-action@v2
              with:
                context: .
                file: ./Dockerfile
                push: true
                tags: learnaksinclass.azurecr.io/myapp:${{github.sha}}

            - name: Azure login
              uses: azure/login@v2
              with:
                creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'

          #  - name: Azure CLI Action
          #    uses: Azure/cli@v2.1.0
            #  with:
             #    # Specify the script here
           #       inlineScript: az aks create -g ${{env.resourceGroup}} -n ${{env.name}} --kubernetes-version $kubernetesVersion --generate-ssh-keys

            - name: Get AKS credentials
              run: |
                    az aks get-credentials --resource-group ${{ env.resourceGroup }} --name ${{ env.name }}

            # Deploy to AKS
            - name: Deploy to AKS
              run: |
                   kubectl apply -f deploy.yml
